### ISSUE TITLE
TargetException error

### ISSUE THREAD

**Issue by lbarasc** [eoctet/llama-java-chat#3]
Under Windows with setting.conf

D:\chat-console>java -jar chat-console.jar --model Llama2 --system 'YOUR_PROMPT'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.ExceptionInInitializerError
        at chat.octet.model.LlamaService.<clinit>(LlamaService.java:28)
        at chat.octet.model.Model.getLlamaModelParameters(Model.java:80)
        at chat.octet.model.Model.<init>(Model.java:57)
        at chat.octet.api.ModelBuilder.getModel(ModelBuilder.java:50)
        at chat.octet.AppConsole.main(AppConsole.java:85)
        ... 8 more
Caused by: chat.octet.model.exceptions.ModelException: Loading native library error
        at chat.octet.model.utils.Platform.loadLibraryResource(Platform.java:123)
        at chat.octet.model.utils.Platform.<clinit>(Platform.java:221)
        ... 13 more
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at chat.octet.model.utils.Platform.loadLibraryResource(Platform.java:114)
        ... 14 more

**Comment by eoctet** [comment]
@lbarasc 

This is a known bug in `llama-java-core` old version, please download the latest version v1.1.6
